// progressionHarmonies.js
export const progressionBank = {
  'I V': [
    ['I', 'V', 'I'],
    ['V', 'I'],
    ['I', 'V', 'V', 'I'],
    ['I', 'V', 'I', 'V'],
    ['V', 'I', 'V', 'I'],
    ['I', 'V', 'I', 'I', 'V'],
  ],
  'I IV V': [
    ['I', 'IV', 'V', 'I'],
    ['I', 'V', 'IV', 'V'],
    ['I', 'IV', 'V', 'IV', 'I'],
    ['I', 'IV', 'I', 'V', 'I'],
    ['I', 'V', 'IV', 'I', 'V'],
    ['I', 'IV', 'V', 'I', 'IV'],
    ['I', 'V', 'I', 'IV', 'V', 'I'],
  ],
  'I IV V VI': [
    ['I', 'IV', 'VI', 'I'],
    ['I', 'VI', 'IV', 'V', 'I'],
    ['I', 'IV', 'V', 'VI', 'I'],
    ['I', 'VI', 'IV', 'V'],
    ['I', 'V', 'VI', 'IV', 'I'],
    ['I', 'IV', 'VI', 'V', 'I'],
    ['I', 'VI', 'I', 'IV', 'V'],
    ['I', 'IV', 'V', 'VI', 'IV', 'I'],
  ],
  'I IV V VI II': [
    ['I', 'IV', 'V', 'VI', 'II', 'I'],
    ['I', 'VI', 'II', 'IV', 'V', 'I'],
    ['I', 'IV', 'V', 'II', 'VI', 'I'],
    ['I', 'II', 'VI', 'IV', 'V'],
    ['I', 'V', 'II', 'VI', 'IV', 'I'],
    ['I', 'IV', 'II', 'V', 'VI', 'I'],
    ['I', 'VI', 'IV', 'II', 'V', 'I'],
    ['I', 'II', 'V', 'VI', 'IV', 'I', 'V'],
  ],
  'I IV V VI II III': [
    ['I', 'IV', 'V', 'VI', 'II', 'III', 'I'],
    ['I', 'VI', 'II', 'III', 'IV', 'V', 'I'],
    ['I', 'IV', 'V', 'II', 'III', 'VI', 'I'],
    ['I', 'III', 'VI', 'II', 'IV', 'V'],
    ['I', 'II', 'III', 'VI', 'IV', 'V', 'I'],
    ['I', 'V', 'VI', 'II', 'III', 'IV', 'I'],
    ['I', 'IV', 'II', 'III', 'VI', 'V', 'I'],
    ['I', 'III', 'II', 'VI', 'IV', 'V', 'I'],
    ['I', 'II', 'III', 'IV', 'V', 'I'],
  ],
  'I IV V VI II III VII': [
    ['I', 'IV', 'V', 'VI', 'II', 'III', 'VII', 'I'],
    ['I', 'VI', 'II', 'III', 'VII', 'IV', 'V', 'I'],
    ['I', 'IV', 'V', 'II', 'III', 'VI', 'VII', 'I'],
    ['I', 'VII', 'III', 'VI', 'II', 'IV', 'V'],
    ['I', 'II', 'III', 'VII', 'VI', 'IV', 'V', 'I'],
    ['I', 'V', 'VI', 'II', 'VII', 'III', 'IV', 'I'],
    ['I', 'IV', 'VII', 'III', 'II', 'VI', 'V', 'I'],
    ['I', 'VI', 'II', 'VII', 'III', 'IV', 'V', 'I'],
  ],
'I IV V VI II III VII V7/ii': [
  ['I', 'V7/ii', 'II', 'V', 'I'],
  ['I', 'V7/ii', 'II', 'IV', 'I'],
  ['I', 'V7/ii', 'II', 'VII', 'I'],
  ['I', 'IV', 'VI', 'V7/ii', 'II'],
  ['VI', 'V7/ii', 'II', 'V', 'I'],
  ['VI', 'V7/ii', 'II', 'I', 'V'],
  ['VI', 'V7/ii', 'II', 'III', 'I'],
  ['I', 'VI', 'V7/ii', 'II', 'I'],
],
};